# Generated by Django 5.0.6 on 2024-05-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0002_initial'),
        ('users', '0002_alter_customuser_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armiya.historyballs'),
        ),
    ]
