# Generated by Django 5.0.6 on 2024-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reyting',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
