# Generated by Django 5.0.6 on 2024-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_reyting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reyting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
