# Generated by Django 5.0.6 on 2024-05-27 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ekb_name', models.CharField(max_length=200)),
                ('ekb', models.IntegerField()),
                ('boshlangich_narx', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=40)),
                ('ball', models.IntegerField()),
                ('definition', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ball', models.IntegerField()),
                ('definition', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('definition', models.CharField(max_length=250)),
                ('ball', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auktsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kuni', models.DateField()),
                ('yutganlar', models.CharField(max_length=100)),
                ('buyumlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.buyum')),
            ],
        ),
    ]
