# Generated by Django 5.0.6 on 2024-05-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armiya', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=200),
        ),
        migrations.CreateModel(
            name='Balls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Asked', 'Asked'), ('Expected', 'Expected'), ('Done', 'Done')], max_length=40)),
                ('ball', models.IntegerField()),
                ('definition', models.CharField(max_length=250)),
                ('tasks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armiya.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='historyballs',
            name='balls_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armiya.balls'),
            preserve_default=False,
        ),
    ]
